print(2 ** 3)
print(22 % 8)
print(22 // 8)
print(22 / 8)
print(3 * 3)
print(5 -2)
print(2 + 2)

nome= input ('Qual sue nome?')
sobrenome= input ('Qual seu sobrenome?')
idade= input ('Qual sua idade?')
print(nome, sobrenome, idade)